// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Doubler$Doubler(Props) {
  var setCount = Props.setCount;
  var $$double = function (param) {
    return Curry._1(setCount, (function (prev) {
                  return prev + prev | 0;
                }));
  };
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: $$double
                }, "double"));
}

var Doubler = {
  make: Doubler$Doubler
};

exports.Doubler = Doubler;
/* react Not a pure module */
