// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Home$Home(Props) {
  return React.createElement("div", undefined, "HOME");
}

var Home = {
  make: Home$Home
};

exports.Home = Home;
/* react Not a pure module */
