// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function PageNotFound$PageNotFound(Props) {
  return React.createElement("div", undefined, "404");
}

var PageNotFound = {
  make: PageNotFound$PageNotFound
};

exports.PageNotFound = PageNotFound;
/* react Not a pure module */
