// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Posts$Posts(Props) {
  return React.createElement("div", undefined, "Posts", React.createElement("ul", undefined, React.createElement("li", undefined, "post 1"), React.createElement("li", undefined, "post 2")));
}

var Posts = {
  make: Posts$Posts
};

exports.Posts = Posts;
/* react Not a pure module */
